name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.7.21379.14'
      - name: display branch name
        run: echo ${{ github.ref_name }}
      - name: Version Bump
        run: |
          $branch = "${{ github.ref }}"
          $version = $branch -replace 'refs/heads/', '' -replace '([0-9]+)\.([0-9]+)\/(.+)', '$1.$2.$env:GITHUB_RUN_NUMBER'
       
      - name: Commit and push changes
        run: |
          git config user.name "Anthony Peiris"
          git config user.email "mapeiris@hotmail.com"
          git add .
          git commit -m "Bump version number"
          git push origin master
