name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.7.21379.14'

      - name: Version Bump
        run: |
         $version = [System.Version]::Parse("${{ github.ref_name }}/0")
          dotnet build /p:Version=$version    
      - name: Commit and push changes
        run: |
          git config user.name "Anthony Peiris"
          git config user.email "mapeiris@hotmail.com"
          git add .
          git commit -m "Bump version number"
          git push origin main
