name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x' 
      - name: display branch name
        run: echo ${{ github.ref_name }}
      - name: Version Bump
        run: |
          $branch = "${{ github.ref }}"
          $version = $branch -replace 'refs/heads/(.+)', '$1' -replace '/', '.'
          dotnet build /p:Version=$version
      - name: display version
        run: echo ${{ version }}
       
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version number"
          commit_options: "--author='Github Actions <actions@github.com>'"
          repository: "."
          branch: ${{ github.head_ref }}
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_gpg_sign: false
          access_token: ${{ secrets.github_token }}

